### PR TITLE
Fix month days for 2081 Jestha and Ashar

### PR DESCRIPTION
**Pull request by pabin**

### CODE REVIEW

**Comment by subeshb1** [comment]
Thank you for the fix @pabin. I'll add this in the next release. I have some an issue to fix https://github.com/subeshb1/Nepali-Date/issues/42 which I'll plan to do during the weekends. Once that's done I'll release this fix

**Comment by subeshb1** [comment]
@pabin Would you mind linking the source where you found the dates? 

The sources I've been following have 31 for Jestha and 32 for Ashar


Hamro Patro
https://english.hamropatro.com/calendar/2081/2
https://english.hamropatro.com/calendar/2081/3


Nepali Calendar
https://nepalicalendar.rat32.com/2081/jestha
https://nepalicalendar.rat32.com/2081/ashad

**Comment by pabin** [comment]
It was confusing to me as well since I also found 2 different dates in different calendars

Calendars with 32 Jestha and 31 Ashar:
https://nepalipatro.com.np/calendar/monthly/bs/2081/2
https://www.hamropatro.com/calendar/2081/2
https://www.ashesh.com.np/nepali-calendar/?year=2081&month=Jestha

I am considering nepalipatro as official here.

Let's wait and confirm the dates before merging.

**Comment by pabin** [comment]
Hello Subesh,

I am contacting you through this thread since I couldn't find your email.

We already met virtually for PR discussion as you can see in this email
thread.

Recently I have been looking for a job, and found your company is hiring.

Currently I am working as a solo developer on my product *Karod - Digital
Kahata* mobile app, because of my family situation I had to look for jobs.
I have attached a resume for your reference.

My app link:
https://play.google.com/store/apps/details?id=com.karod

I am really bad at interviews. Is there any way it can work with
recommendations ?

Thanks and regards.
PABIN

**Comment by rajbinms** [comment]
Hey! Jumping in @subeshb1 @pabin has this been included in the release yet? I see dates for Falgun (30 to 29) and Chaitra (30 to 31) for the 2081 calendar.

**Comment by pabin** [comment]
hey @subeshb1 can you confirm now and review the PR please, I have also updated the total days for falgun and chaitra 2081 as the issue raised by @rajbinms also seems right

**Review by subeshb1 — APPROVED** [review]

**Comment by subeshb1** [comment]
Thanks for jumping into this @pabin and @rajbinms. I'll merge and release the fix

**Pull request merged**
